name: mi_card
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hexcolor: ^2.0.3

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - images/avatar.jpg
   - images/asysnetLogo.png

  fonts:
    - family: ubuntu
      fonts:
        - asset: fonts/Ubuntu-Bold.ttf

    - family: monoton
      fonts:
        - asset: fonts/Monoton.ttf
