# This is a basic workflow to help you get started with Actions
name: Flutter Web
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release
      - run: |
          cd build/web
          git init
          git config --global user.email gonzalomatarrubia@hotmail.com
          git config --global user.name gmatarrubia
          git status
          git remote add origin https://${{secrets.commit_secret}}@github.com/gmatarrubia/id_card.git
          git checkout -b web
          git add --all
          git commit -m "update"
          git push origin web -f
